HTML-Forms Project
Angelesh1995/HTML-Forms pull request #1
Opened 2020-01-22 21:08 UTC by Angelesh1995

This project consists of building an HTML page and form that matches the INTUIT Sign Up page.

2020-01-22 21:33 UTC, kobiyoyo commented
### Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-01-22 22:08 UTC, kobiyoyo requested changes
## Hi Team  ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are few more things required. 

## General
- [ ] Please let's add linters to your project.
- https://github.com/microverseinc/linters-config/tree/master/css
![1](https://user-images.githubusercontent.com/23278161/72872182-fd6dc780-3cec-11ea-9462-98e5ae325b72.png)
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload and fix errors.
![6](https://user-images.githubusercontent.com/23278161/72938824-f20db100-3d6b-11ea-9feb-040f19122a52.png)

## Form
- [ ] The Phone `<input>` type shouldn't be `text` 

[OPTIONAL] -  [`<nav>` tag](http://html5doctor.com/nav-element/) should be used for  major navigation links

### Make changes and submit another code review request.
*Happy coding*

2020-01-22 22:14 UTC, kobiyoyo requested changes

2020-01-22 22:14 UTC, kobiyoyo commented on index.html
> +                  <input type="text" name="phone-number" id="text">
I recommend using **tel** for input type

2020-01-23 17:24 UTC, closed without merging

2020-02-07 20:06 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-07 20:19 UTC, addod19 reviewed
## Status: Require changes 🔴 

Hi, @Angelesh1995  and @dansantander,:+1: great job implementing some of the changes requested by the previous reviewer. However, there are some requirements left out. Find comment below: 
- Kindly enable stickler this repo. Go [here](https://stickler-ci.com/) to enable stickler.
- Kindly fix the error returned by [css validator](https://jigsaw.w3.org/css-validator)
![fsleep](https://user-images.githubusercontent.com/46388113/74062815-04801f80-49e7-11ea-9ef8-94d890fd8aea.PNG)

Make these changes and submit code review 🙂 
Happy coding 💻 
Daniel Larbi Addo